name: Hourly Air Quality ETL

# This section controls WHEN the robot runs
on:
  schedule:
    # "cron" is a time syntax. '0 * * * *' means "Run at minute 0 of every hour"
    - cron: '0 * * * *'
  # This allows us to click the "Run Now" button manually for testing
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest  # We ask GitHub for a free Linux server

    steps:
      # Step 1: Download our code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Python on the server
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install the libraries our script needs (Pandas, Requests, etc.)
      - name: Install dependencies
        run: |
          pip install requests psycopg2-binary pandas

      # Step 4: Run the Python script
      # IMPORTANT: We inject the passwords (Secrets) here so the script can use them
      - name: Run ETL Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_URI: ${{ secrets.DB_URI }}
        run: python fetch_data.py